### ISSUE TITLE
Separar as informações em diferentes documentos, aplicar correções e usar formato Markdown

### ISSUE THREAD

**Issue by victor-sobreira** [pel0ta/trabalho-grupo-2#3]
Em relação ao [arquivo gerado](https://github.com/pel0ta/trabalho-grupo-2/blob/master/Primeira-reuniao_Marcus) após reunião com prof. Sorandra:
   - [ ] Separar as informações em arquivos distintos (Visão e Caso de Negócio, Minuta, ...).
   - [ ] Revisar a escrita e corrigir erros de formatação/ortográficos/texto cortado.
   - [ ] Usar formato Markdown.

O mesmo se aplica aos demais arquivos: [proposta Leonardo](https://github.com/pel0ta/trabalho-grupo-2/blob/master/EntrevistaComLeonardoMiquelutti) e [proposta Suelem](https://github.com/pel0ta/trabalho-grupo-2/blob/master/Tulio/Minuta%20Tulio.md)

**Comment by tuliomt** [comment]
> Em relação ao [arquivo criado](https://github.com/pel0ta/trabalho-grupo-2/blob/master/Primeira-reuniao_Marcus) após reunião com prof. Sorandra:
> 
> * [ ]  Separar como informações em arquivos distintos (Visão e Caso de Negócio, Minuta, ...).
> * [ ]  Revise a escrita e corrija erros de formatação / ortográficos / texto cortado.
> * [ ]  Usar formato Markdown.
> 
> O mesmo se aplica aos demais arquivos: [proposta Leonardo](https://github.com/pel0ta/trabalho-grupo-2/blob/master/EntrevistaComLeonardoMiquelutti) e [proposta Suelem](https://github.com/pel0ta/trabalho-grupo-2/blob/master/Tulio/Minuta%20Tulio.md)

corrigido
