### ISSUE TITLE
Ajustes na estrutura de pastas

### ISSUE THREAD

**Issue by victor-sobreira** [pel0ta/trabalho-grupo-2#5]
Sugiro a seguinte estrutura de pastas para armazenar os artefatos de documentação:

* docs
  * minutas
      * 2019.08.27_14h00m_{identificacao}.md
  * modelos
      * diagrama_casos_de_uso_{identificacao}.png
      * visao_caso_negocio_{identificacao}.md
      * riscos_{identificacao}.md
  * glossario_{identificacao}.md

Onde, {identificacao} pode ser o nome provisório do sistema, nome do contato/colaborador, … Fica a critério do grupo. Só mantenham a consistência e evitem nomes muito compridos, especialmente para pastas.

**Comment by tuliomt** [comment]
> Sugerir a seguinte estrutura de massas para armazenar os artefatos de uso:
> 
> * docs
>   
>   * minutas
>     
>     * 2019.08.27_14h00m_ {identificacao} .md
>   * modelos
>     
>     * diagrama_casos_de_uso_ {identificacao} .png
>     * visao_caso_negocio_ {identificacao} .md
>     * riscos_ {identificacao} .md
>   * glossario_ {identificacao} .md
> 
> Onde, {identificação} pode ser o nome provisório do sistema, o nome do contato / colaborador,… Fica a critério do grupo. Só mantenha uma consistência e evite nomes muito compridos, especialmente para massas.

corrigido
